version: "3"
services:
  mongo:
    image: mongo
    restart: always
  mongo-express:
    image: mongo-express
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "8081:8081"
  node:
    build: .